### ISSUE TITLE
assert os.path.isdir(dir), '%s is not a valid directory' % dir AssertionError: /.111 is not a valid directory

### ISSUE THREAD

**Issue by yff0815** [KupynOrest/DeblurGAN#109]

**Comment by yff0815** [comment]
when i run this code the result is:
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: /.111
dataset_mode: single
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
learn_residual: True
loadSizeX: 640
loadSizeY: 360
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleImageDataset] was created
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/yff/PycharmProjects/gan_terminal/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/yff/PycharmProjects/gan_terminal/data/custom_dataset_data_loader.py", line 30, in initialize
    self.dataset = CreateDataset(opt)
  File "/home/yff/PycharmProjects/gan_terminal/data/custom_dataset_data_loader.py", line 20, in CreateDataset
    dataset.initialize(opt)
  File "/home/yff/PycharmProjects/gan_terminal/data/single_dataset.py", line 14, in initialize
    self.A_paths = make_dataset(self.dir_A)
  File "/home/yff/PycharmProjects/gan_terminal/data/image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: /.111 is not a valid directory

**Comment by yff0815** [comment]
and i put one blurry image in the directory 111

**Comment by hanshan1** [comment]
you can try 
 python test.py --dataroot ./111 --model test --dataset_mode single --learn_residual

**Comment by yff0815** [comment]
谢谢~
