### ISSUE TITLE
Unexpected device_id

### ISSUE THREAD

**Issue by mersaint** [KupynOrest/DeblurGAN#11]
When testing the code, I got: TypeError: cuda() got an unexpected keyword argument 'device_id'
at: File "./models/networks.py", line 53, in define_G netG.cuda(device_id=gpu_ids[0]).
The device_id was printed as 0 in my platform, with the log below:

------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./images/blurred_sharp/blurred
dataset_mode: single
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
learn_residual: True
loadSizeX: 640
loadSizeY: 360
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleImageDataset] was created
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "./models/models.py", line 11, in create_model
    model.initialize(opt)
  File "./models/test_model.py", line 20, in initialize
    opt.learn_residual)
  File "./models/networks.py", line 53, in define_G
    netG.cuda(device_id=gpu_ids[0])
TypeError: cuda() got an unexpected keyword argument 'device_id'

**Comment by mersaint** [comment]
I solved the problem by replacing netG.cuda(device_id=gpu_ids[0]) with netG.cuda(gpu_ids[0]).
