### ISSUE TITLE
Can someone please upload a requirements file to run the code? 

### ISSUE THREAD

**Issue by cardyfib** [KupynOrest/DeblurGAN#112]
I am trying to run the test code but I keep getting some dependency errors which I am pretty sure is happening because I got the wrong version of some package. It would be great if you could upload the requirements text file. Thanks a lot! @KupynOrest

**Comment by cardyfib** [comment]
I found the following to be the requirements:
python==3.6
torch==0.3.1
torchvision==0.2.1
dominate==2.3.1
visdom==0.1.8.3
opencv-python
cython
pyyaml

**Comment by MarStarck** [comment]
+ pyssim

**Comment by Harsharma2308** [comment]
Also pillow==6.1

**Comment by Harsharma2308** [comment]
After running the above setup I face an error though-
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "/home/harsh/codespace/DeblurGAN/models/models.py", line 8, in create_model
    model = TestModel( opt )
  File "/home/harsh/codespace/DeblurGAN/models/test_model.py", line 20, in __init__
    opt.learn_residual)
  File "/home/harsh/codespace/DeblurGAN/models/networks.py", line 46, in define_G
    gpu_ids=gpu_ids, use_parallel=use_parallel, learn_residual=learn_residual)
  File "/home/harsh/codespace/DeblurGAN/models/networks.py", line 124, in __init__
    norm_layer(ngf),
TypeError: __init__() got an unexpected keyword argument 'track_running_stats'


```
