### ISSUE TITLE
train.py IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

### ISSUE THREAD

**Issue by jingjiing** [KupynOrest/DeblurGAN#127]
Hi, thanks for your code!
I just can not run the train.py using the given data. Do anybody know how to solve this problem?
Following is the error message.
Thanks!

#training images = 1151
PSNR on Train = 13.675619
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    train(opt, data_loader, model)
  File "train.py", line 31, in train
    errors = model.get_current_errors()
  File "/home/bloch/ggh/gantest/DeblurGAN-master/models/conditional_gan_model.py", line 118, in get_current_errors
    return OrderedDict([('G_GAN', self.loss_G_GAN.data[0]),
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by jingjiing** [comment]
I changed the self.loss_G_GAN.data[0] to self.loss_G_GAN.data
