### ISSUE TITLE
got an unexpected keyword argument 'track_running_stats'

### ISSUE THREAD

**Issue by SumNeuron** [KupynOrest/DeblurGAN#144]
Was facing this issue https://github.com/KupynOrest/DeblurGAN/issues/143

which lead to:

```
AttributeError: 'SingleDataset' object has no attribute 'A_paths'
```

following the suggestion in this issue:

https://github.com/KupynOrest/DeblurGAN/issues/137

added updates to files specified here:

https://github.com/KupynOrest/DeblurGAN/pull/138/files

which now gives me:

Opt.nThreads =  1
dataset [SingleImageDataset] was created
CustomDatasetDataLoader
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "/home/sumner/Projects/DeblurGAN/models/models.py", line 8, in create_model
    model = TestModel( opt )
  File "/home/sumner/Projects/DeblurGAN/models/test_model.py", line 19, in __init__
    opt.learn_residual)
  File "/home/sumner/Projects/DeblurGAN/models/networks.py", line 46, in define_G
    gpu_ids=gpu_ids, use_parallel=use_parallel, learn_residual=learn_residual)
  File "/home/sumner/Projects/DeblurGAN/models/networks.py", line 124, in __init__
    norm_layer(ngf),
TypeError: __init__() got an unexpected keyword argument 'track_running_stats'

**Comment by jhonpj** [comment]
hi,do you solve the problem?
TypeError: init() got an unexpected keyword argument 'track_running_stats'
i also have a same error,can you help me, thank you very much.
