### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url

### ISSUE THREAD

**Issue by lz931585538** [KupynOrest/DeblurGAN#169]
When I run train.py ,it comes this question.
What should I do to solve this?

Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ibian/.local/lib/python2.7/site-packages/visdom-0.1.8.8-py2.7.egg/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe40c191090>: Failed to establish a new connection: [Errno 111] Connection refused',))
(epoch: 28, iters: 2006, time: 0.059) G_GAN: 17.543 G_L1: 580.609 D_real+fake: 0.000 
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ibian/.local/lib/python2.7/site-packages/visdom-0.1.8.8-py2.7.egg/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ibian/.local/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe40013cd10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mardukbp** [comment]
First you have to start the visdom server (`python -m visdom.server`). Hopefully this solves the problem.
