### ISSUE TITLE
AttributeError: 'SingleDataset' object has no attribute 'A_paths'

### ISSUE THREAD

**Issue by obelling** [KupynOrest/DeblurGAN#171]
when I test with my own blur picture,by python test.py --dataroot path --model test --dataset_mode single --learn_residual,I met this problem,How can I solve this problem?

**Comment by obelling** [comment]
I fix code by #138 ,however it does not work .erorr as follow:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Program Files (x86)\ANACONDA\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Program Files (x86)\ANACONDA\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Program Files (x86)\ANACONDA\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\CODE\DeblurGAN-master\test.py", line 31, in <module>
    for i, data in enumerate(dataset):
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "D:\Program Files (x86)\ANACONDA\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    for i, data in enumerate(dataset):
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "D:\Program Files (x86)\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 21548) exited unexpectedly

**Comment by tungvd345** [comment]
set "opt.nThreads = 0   # test code only supports nThreads = 1" in _test.py_ to solved

**Comment by obelling** [comment]
> set "opt.nThreads = 0   # test code only supports nThreads = 1" in test.py to solved

Thanks,I try and it works,I'm appreciate your help,but I don't understand why?

**Comment by obelling** [comment]
By the way ,Does the processed image directly replace the original one?

**Comment by tungvd345** [comment]
> > set "opt.nThreads = 0   # test code only supports nThreads = 1" in test.py to solved
> 
> Thanks,I try and it works,I'm appreciate your help,but I don't understand why?

because test model supports only one thread and index thread is from 0,1,2...So, you set opt,nTheads = 0

**Comment by obelling** [comment]
@tungvd345 Excuse me,have you ever tested with your own datas?I've tested it with my own datas, and I've tried it with the pictures provided by the authors, but they've had little effect neither.

**Comment by YXKN** [comment]
> @tungvd345 Excuse me,have you ever tested with your own datas?I've tested it with my own datas, and I've tried it with the pictures provided by the authors, but they've had little effect neither.

I have the same problem. Have you solved this problem now?

**Comment by tungvd345** [comment]
sorry for the late reply, I think it is not compatible with your work. In my data, it is effective

**Comment by YXKN** [comment]
> sorry for the late reply, I think it is not compatible with your work. In my data, it is effective

Thanks a lot. I will figure it out.

**Comment by LIMENG0307** [comment]
> > sorry for the late reply, I think it is not compatible with your work. In my data, it is effective
> 
> Thanks a lot. I will figure it out.

hello how can you solved this problem
