### ISSUE TITLE
For training, directory error.

### ISSUE THREAD

**Issue by HeoJinLareine** [KupynOrest/DeblurGAN#174]
python train.py --dataroot ./AB --learn_residual --resize_or_crop crop --fineSize 256 

I put this line but error saids..
-------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    data_loader = CreateDataLoader(opt)
  File "/Users/heojin/Desktop/Mydev/DeblurGAN/DeblurGAN-kupynOrest/data/data_loader.py", line 4, in CreateDataLoader
    data_loader = CustomDatasetDataLoader(opt)
  File "/Users/heojin/Desktop/Mydev/DeblurGAN/DeblurGAN-kupynOrest/data/custom_dataset_data_loader.py", line 32, in __init__
    self.dataset = CreateDataset(opt)
  File "/Users/heojin/Desktop/Mydev/DeblurGAN/DeblurGAN-kupynOrest/data/custom_dataset_data_loader.py", line 9, in CreateDataset
    dataset = AlignedDataset(opt)
  File "/Users/heojin/Desktop/Mydev/DeblurGAN/DeblurGAN-kupynOrest/data/aligned_dataset.py", line 17, in __init__
    self.AB_paths = sorted(make_dataset(self.dir_AB))
  File "/Users/heojin/Desktop/Mydev/DeblurGAN/DeblurGAN-kupynOrest/data/image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: D:\Photos\TrainingData\BlurredSharp\combined/train is not a valid directory
-------------------------------------------------------------------------------------------

Do you know how to fix this?

**Comment by ghost** [comment]
hello , I encountered the same problem as you. Have you solved it? Can you tell me how to solve it ? my email is 1240332487@qq.com , thank you
