### ISSUE TITLE
There is a "RuntimeError" when  I use this command to run the program

### ISSUE THREAD

**Issue by dapsjj** [KupynOrest/DeblurGAN#22]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

How to fix it?

**Comment by ilei00** [comment]
I met the same question.If you have solved it ,please show your solution!

**Comment by KupynOrest** [comment]
Hello, unfortunately I am not able to test it on Windows but it seems that you have troubles with multiprocessing, try this - https://medium.com/@mackie__m/running-a-cifar-10-image-classifier-on-windows-with-pytorch-9094e29089cd

**Comment by robbiewongBD** [comment]
I (almost) fixed the error by using "if __name__ == '__main__':", and another error occurs (with windows10 64bit system) like this:
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    for i, data in enumerate(dataset):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_transform.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by mardukbp** [comment]
To fix this issue the code after the imports in `test.py` must be the body of this `if`:

```py
if __name__ == '__main__':
    <original code in test.py>
```
