### ISSUE TITLE
How to get deblurred images of full resolution in test?

### ISSUE THREAD

**Issue by Deephome** [KupynOrest/DeblurGAN#33]
Hello, I test the model on  my images (1333x764) using following command , but I get 256x256 deblurred images, how can I  get deblurred images of original resolution ？

python test.py --dataroot /.path_to_your_data --model test --dataset_mode single --learn_residual

It seems that the model cropped the image ，but i dont know how to avoid it.

**Comment by diegotessarollo** [comment]
@Deephome How you execute test without the latest G model?

**Comment by hrbspider** [comment]
It seems impossible to get deblurred images of resolution using the current options in base_options.py or test_options.py. You should crop the original image into blocks and deblur these blocks, then combine all the deblurred blocks into one whole image.

**Comment by hhliao** [comment]
@hrbspider the defulat Options using resize_and_crop.

**Comment by hrbspider** [comment]
@hhliao Yes, just set the `loadSizeX` and `fineSize` same as image size. So, resize_and_crop does nothing on image.

**Comment by Deephome** [comment]
1) @diegotessarollo   I downloaded it very early.
2) a solution to my question. Just add another  option " no_change " for  argument  ''resize_or_crop'',and use no_change in test, so the transformer don't crop the image.

**Comment by ProGamerGov** [comment]
I tried testing different values for `--loadSizeX`, `--loadSizeY`, and `--fineSize`, and got this error:  

```
Total number of parameters: 11378179
-----------------------------------------------
model [TestModel] was created
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    for i, data in enumerate(dataset):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/DeblurGAN/data/single_dataset.py", line 25, in __getitem__
    A_img = self.transform(A_img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 286, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py", line 272, in get_params
    j = random.randint(0, w - tw)
  File "/usr/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-479, -479)

ubuntu@ip-Address:~/DeblurGAN$
```
