### ISSUE TITLE
RuntimeError: The size of tensor a (170) must match the size of tensor b (172) at non-singleton dimension 2

### ISSUE THREAD

**Issue by lpnueg4** [KupynOrest/DeblurGAN#38]
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    model.test()
  File "/root/DeblurGAN/models/test_model.py", line 40, in test
    self.fake_B = self.netG.forward(self.real_A)
  File "/root/DeblurGAN/models/networks.py", line 155, in forward
    output = input + output
RuntimeError: The size of tensor a (170) must match the size of tensor b (172) at non-singleton dimension 2

**Comment by lpnueg4** [comment]
output~[torch.cuda.FloatTensor of size 1x3x172x256 (GPU 0)]
input~[torch.cuda.FloatTensor of size 1x3x170x256 (GPU 0)]
Why input and output not same?

**Comment by lpnueg4** [comment]
use cmd: python3 test.py --dataroot ./testimage  --model test --dataset_mode single --learn_residual --resize_or_crop scale_width

**Comment by KupynOrest** [comment]
I have the same problems with some image dimensions, it seems that pytorch strided convolution / transposed convolution blocks give the right output in 100% cases only if the input image size os of the power of 2. What I can advice is to resize your images to 256x256 and try to run the model again

**Comment by pengjingg** [comment]
@KupynOrest If so, how you generated output images that keep the ratio of original input images that you show in your paper and github?

**Comment by drafly** [comment]
@KupynOrest I thought the key problem is the size of the input image, if the size of the image can be divided by 4, there will be no error about the tensor dimension occurred. We can analyze the problem deeply. DeblurGAN implemented 4 times downsampling, if the original size of the input image cannot be divided by 4, the deconv2d operation would generate the wrong tensor size compared with the input size. 
For instance, image size: 21*56 -> 11*28 -> 6*14 -> ... -> 6*14 -> 12*28 -> 24*56, it will cause the error mentioned above.

**Comment by lvzhihan** [comment]
You should change finasize in base_option into the width of the picture. And remain only one picture in the input folder(or else the memory will be error). And then run test.py, you can get that you want.
