### ISSUE TITLE
When I run the model ,I meet the error：

### ISSUE THREAD

**Issue by 10183308** [KupynOrest/DeblurGAN#4]
When I run the model ,I meet the error：
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: images/
dataset_mode: single
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
learn_residual: True
loadSizeX: 640
loadSizeY: 360
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleImageDataset] was created
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    for i, (data,_) in enumerate(dataset):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/media_share/linkfile/DeblurGAN/data/single_dataset.py", line 25, in __getitem__
    A_img = self.transform(A_img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms.py", line 29, in __call__
    img = t(img)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/transforms.py", line 139, in __call__
    ow = int(self.size * w / h)
TypeError: unsupported operand type(s) for /: 'list' and 'int'

**Comment by 10183308** [comment]
Please reply me ?

thank you very much

**Comment by KupynOrest** [comment]
Could you provide more details? What is the size of your images? I would try to reproduce it

**Comment by liupengfei1234** [comment]
Have you already solve the problem, I meet the same issue~

**Comment by pengjingg** [comment]
I met the error in one server, and after I cloned the code into another server, the problem solved. Don't know why.

**Comment by marcosly** [comment]
Any one solved this issue? I met the same problem

**Comment by marcosly** [comment]
@10183308 did you solved the problem

**Comment by marcosly** [comment]
@liupengfei1234 did you solved the issue?

**Comment by vincentlooi** [comment]
You need to update torchvision

**Comment by kartik-nighania** [comment]
updating torchvision didnt helped me
in the error the transform.py filepath is mention. I corrected the error by using int values from list. 
``class Scale(object):
    """Rescales the input PIL.Image to the given 'size'.
    'size' will be the size of the smaller edge.
    For example, if height > width, then image will be
    rescaled to (size * height / width, `size)`
    size: size of the smaller edge
    interpolation: Default: PIL.Image.BILINEAR
    """

    def __init__(self, size, interpolation=Image.BILINEAR):
        self.size = size
        self.interpolation = interpolation

    def __call__(self, img):
        w, h = img.size
        if (w <= h and w == self.size[0]) or (h <= w and h == self.size[1]):
            return img
        if w < h:
            ow = self.size[0]
            oh = int(self.size[1] * h / w)
            return img.resize((ow, oh), self.interpolation)
        else:
            oh = self.size[1]
            ow = int(self.size[0] * w / h)
            return img.resize((ow, oh), self.interpolation)

**Comment by ski133** [comment]
@liupengfei1234  can you tell me how to fix the NotADirectoryError ?Thank you !!!
