### ISSUE TITLE
I update the networks.py, but it rises a error(Test mode).

### ISSUE THREAD

**Issue by knaffe** [KupynOrest/DeblurGAN#55]
RuntimeError: While copying the parameter named model.19.weight, whose dimensions in the model are torch.Size([256, 128, 4, 4]) and whose dimensions in the checkpoint are torch.Size([256, 128, 3, 3]).
But if I use the old files(but fixed the device_id errors), it can work.
I checked the change log, I found that the ConvTranspose2d settings were changed.
Why do you  add this change?  What is the improvement of it?

command line:
python test.py --dataroot testimage --model test  --dataset_mode single --learn_residual
output:

------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: testimage
dataset_mode: single
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
learn_residual: True
loadSizeX: 640
loadSizeY: 360
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleImageDataset] was created
/home/chilam/anaconda3/envs/py36/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "/home/chilam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "/home/chilam/workspace/DeblurGAN/models/models.py", line 11, in create_model
    model.initialize(opt)
  File "/home/chilam/workspace/DeblurGAN/models/test_model.py", line 21, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/chilam/workspace/DeblurGAN/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/chilam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named model.19.weight, whose dimensions in the model are torch.Size([256, 128, 4, 4]) and whose dimensions in the checkpoint are torch.Size([256, 128, 3, 3]).

**Comment by KupynOrest** [comment]
Many thanks for noticing that bug, I changed the parameters in order to avoid checkerboard artifacts while training, i would add the fix in test time to make the model compatible with the weights.

**Comment by IrvingShu** [comment]
@knaffe Did you fix it?

**Comment by knaffe** [comment]
@IrvingShu ，I think it has to be retrained the model to fit the new parameters.
I just rolled back to the old file, it worked without any error.
