### ISSUE TITLE
You may refresh your pretrained weight after changing the model architecture.

### ISSUE THREAD

**Issue by Gasoonjia** [KupynOrest/DeblurGAN#59]
I encountered the following RuntimeError when using pretrained weight to test the image provided in the images directory. It seems that there's some sizes of weight not matched between your current model and your pretrained weight. 

/home/gasoon/main/anaconda3/envs/vd/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "/home/gasoon/main/anaconda3/envs/vd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 514, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCTensorCopy.c:51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    model = create_model(opt)
  File "/media/store/gasoon/code/research/DeblurGAN/models/models.py", line 11, in create_model
    model.initialize(opt)
  File "/media/store/gasoon/code/research/DeblurGAN/models/test_model.py", line 21, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/media/store/gasoon/code/research/DeblurGAN/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/gasoon/main/anaconda3/envs/vd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named model.19.weight, whose dimensions in the model are torch.Size([256, 128, 4, 4]) and whose dimensions in the checkpoint are torch.Size([256, 128, 3, 3]).

After I went through your code record, I found that you changed the kernel size and out_padding value but not refresh your pretrained weight. After changing them back, all the thing went well.

So would you please refresh your pretrained to make us getting the sharpest result? Thank you so much!!!

**Comment by kikyou123** [comment]
I found this question too, how you fix it?

**Comment by Gasoonjia** [comment]
You should roll the code back into the version the author did not change the model architecture (about 1w before), then the model can run normally.
