### ISSUE TITLE
RuntimeError: The size of tensor a (256) must match the size of tensor b (253) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Jasas9754** [KupynOrest/DeblurGAN#67]
```
WARNING: Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    model.test()
  File "C:\Users\motor\pytorch\DeblurGAN\models\test_model.py", line 37, in test
    self.fake_B = self.netG.forward(self.real_A)
  File "C:\Users\motor\pytorch\DeblurGAN\models\networks.py", line 148, in forward
    output = input + output
RuntimeError: The size of tensor a (256) must match the size of tensor b (253) at non-singleton dimension 3

```

with win10 anaconda

what's the problem?

**Comment by zQuantz** [comment]
Same issue here. The problem is the input and output dimensions do not match. Will be looking to find an error today

**Comment by fishman2008** [comment]
I have encountered the same issue. Any suggestions?

**Comment by KupynOrest** [comment]
fixed this issue in latest commit

**Comment by javaDuQing** [comment]
It's still wrong.

**Comment by javaDuQing** [comment]
@zQuantz  Have you solved the problem ?

**Comment by hust-lidelong** [comment]
I met the same problem.too.
RuntimeError: The size of tensor a (191) must match the size of tensor b (192) at non-singleton dimension 2
