### ISSUE TITLE
DeblurGAN  questions

### ISSUE THREAD

**Issue by shiranlyf** [KupynOrest/DeblurGAN#69]
throw a error when i am running "python test.py --dataroot /root/DeblurGAN/dataroot/valA/  --model test --dataset_mode single --learn_residual  --gpu_ids -1"   

error information:
    Traceback (most recent call last):
  File "test.py", line 36, in <module>
    model.test()
  File "/root/DeblurGAN/models/test_model.py", line 37, in test
    self.fake_B = self.netG.forward(self.real_A)
  File "/root/DeblurGAN/models/networks.py", line 148, in forward
    output = input + output
RuntimeError: The size of tensor a (256) must match the size of tensor b (253) at non-singleton dimension 3
root@iZm5e9stm1x1k2a67lr7msZ:~/DeblurGAN# RuntimeError: The size of tensor a (256) must match the size of tensor b (253) at non-singleton dimension 3

**Comment by KupynOrest** [comment]
fixed in latest commit
