### ISSUE TITLE
 TypeError: unsupported operand type(s) for /: 'list' and 'int'

### ISSUE THREAD

**Issue by loralyc** [KupynOrest/DeblurGAN#70]
hello,
when i run the command,`python test.py --dataroot ./test_image --model test --dataset_mode single --learn_residual`
and i put just one image named '1.bmp' into the folder--test_image,
error information:
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    for i, data in enumerate(dataset):
  File "/local/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/local/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/local/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/data2/DeblurGAN/data/single_dataset.py", line 26, in __getitem__
    A_img = self.transform(A_img)
  File "/local/anaconda2/lib/python2.7/site-packages/torchvision-0.1.8-py2.7.egg/torchvision/transforms.py", line 29, in __call__
    img = t(img)
  File "/local/anaconda2/lib/python2.7/site-packages/torchvision-0.1.8-py2.7.egg/torchvision/transforms.py", line 139, in __call__
    ow = int(self.size * w / h)
TypeError: unsupported operand type(s) for /: 'list' and 'int'

is it any special requirement about the --dataroot ？ 
thank you very much.

**Comment by kartik-nighania** [comment]
updating torchvision didnt helped me
in the error the transform.py filepath is mention. I corrected the error by solving the error int values from list. replace the below code with shape function. Its much the same only the size[0] and size[1] is taken instead of size
`
class Scale(object):
"""Rescales the input PIL.Image to the given 'size'.
'size' will be the size of the smaller edge.
For example, if height > width, then image will be
rescaled to (size * height / width, size)
size: size of the smaller edge
interpolation: Default: PIL.Image.BILINEAR
"""

def __init__(self, size, interpolation=Image.BILINEAR):
    self.size = size
    self.interpolation = interpolation

def __call__(self, img):
    w, h = img.size
    if (w <= h and w == self.size[0]) or (h <= w and h == self.size[1]):
        return img
    if w < h:
        ow = self.size[0]
        oh = int(self.size[1] * h / w)
        return img.resize((ow, oh), self.interpolation)
    else:
        oh = self.size[1]
        ow = int(self.size[0] * w / h)
        return img.resize((ow, oh), self.interpolation)

**Comment by Yangchunfighting** [comment]
@kartik-nighania   ![image](https://user-images.githubusercontent.com/40748967/43937907-3e4bd2f2-9c93-11e8-9a9d-6b51e2d2350d.png)
hello .   when i fix the error using your codes ,another error occured. so could u help me  with it.
