### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by juanchen1993** [KupynOrest/DeblurGAN#71]
When I try to run the train.py, it occurs the follow error:

**requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f358302f208>: Failed to establish a new connection: [Errno 111] Connection refused',))**

**Comment by Deephome** [comment]
Just startup the visdom server by using " python -m visdom.server"  and opening localhost website

**Comment by shridhar-pivotchain** [comment]
@Deephome when I tried to run " python -m visdom.server" I got new error 

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1159, in <module>
    download_scripts_and_run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1154, in download_scripts_and_run
    download_scripts()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1032, in download_scripts
    os.makedirs(directory)
  File "/usr/local/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/anaconda3/lib/python3.6/site-packages/visdom/static/fonts'

Will you Please help or do you have any other alternative
