### ISSUE TITLE
RuntimeError: sizes do not match at /b/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:216

### ISSUE THREAD

**Issue by Srijita173** [KupynOrest/DeblurGAN#72]
I am trying to run the code with the pretrained weights from the dropbox . Also I have kept the sample image into the image folder .

model [TestModel] was created
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    model.test()
  File "/home/nikhitha/Srijita_work/deblur/DeblurGAN-master/models/test_model.py", line 37, in test
    self.fake_B = self.netG.forward(self.real_A)
  File "/home/nikhitha/Srijita_work/deblur/DeblurGAN-master/models/networks.py", line 148, in forward
    output = input + output
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 745, in __add__
    return self.add(other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 283, in add
    return self._add(other, False)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 277, in _add
    return Add(inplace)(self, other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/basic_ops.py", line 20, in forward
    return a.add(b)
RuntimeError: sizes do not match at /b/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:216

I am getting the above runtime error while executing

python test.py --dataroot /./home/nikhitha/Srijita_work/deblur/DeblurGAN-master/images --model test --dataset_mode single --learn_residual

**Comment by Srijita173** [comment]
Sorry I wasn't working with the latest commit . Issue has been solved in the latest commit already .
