### ISSUE TITLE
module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by princebhatia09** [KupynOrest/DeblurGAN#74]

**Comment by KupynOrest** [comment]
Could you please specify the error and the command you use to run the code?

**Comment by TarzanWonder** [comment]
(base) C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-master>python t
est.py --dataroot C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-mast
er\blur --model test --dataset_mode single --learn_residual
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    opt = TestOptions().parse()
  File "C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-master\options
\base_options.py", line 61, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\prince.bhatia\AppData\Local\Continuum\anaconda3\lib\site-packag
es\torch\cuda\__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by princebhatia09** [comment]
(base) C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-master>python t
est.py --dataroot C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-mast
er\blur --model test --dataset_mode single --learn_residual
Traceback (most recent call last):
File "test.py", line 13, in
opt = TestOptions().parse()
File "C:\Users\prince.bhatia\Desktop\DeblurGAN-master\DeblurGAN-master\options
\base_options.py", line 61, in parse
torch.cuda.set_device(self.opt.gpu_ids[0])
File "C:\Users\prince.bhatia\AppData\Local\Continuum\anaconda3\lib\site-packag
es\torch\cuda_init_.py", line 262, in set_device
torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

This is the error i received

**Comment by RRRzhou** [comment]
I'm having the same problem ! 
Have you solved it ?

**Comment by freedomofme** [comment]
I found solution, look at here:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/67

**Comment by mvmnt** [comment]
> I found solution, look at here:
> [junyanz/pytorch-CycleGAN-and-pix2pix#67](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/67)

Just tried this and it didn't work. Unsure on how to proceed with this
