### ISSUE TITLE
Error while training.

### ISSUE THREAD

**Issue by shivam2296** [KupynOrest/DeblurGAN#76]
While training for blurred_sharp dataset. I encountered this error: 
I have placed A and B in DeblurGAN/data
-------------------------------------------------------------------------------------------------------------------------------------------
model [ConditionalGANModel] was created
#training images = 2302
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f694efabf60>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    train(opt, data_loader, model, visualizer)
  File "train.py", line 21, in train
    model.optimize_parameters()
  File "/home2/shivam/NewDeblurGAN/models/conditional_gan_model.py", line 108, in optimize_parameters
    self.backward_D()
  File "/home2/shivam/NewDeblurGAN/models/conditional_gan_model.py", line 92, in backward_D
    self.loss_D.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by KupynOrest** [comment]
Which pytorch version do you use?

**Comment by shivam2296** [comment]
0.4.0
