### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by shridhar-pivotchain** [KupynOrest/DeblurGAN#85]
Hi guys,
While running 
python test.py --dataroot /.path_to_your_data --model test --dataset_mode single --learn_residual
I got into the following Error. Can Someone help me out

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f37d328bd30>: Failed to establish a new connection: [Errno 111]
 Connection refused

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 431, in _send
    data=json.dumps(msg),
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectio
nError('<urllib3.connection.HTTPConnection object at 0x7f37d328bd30>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2018-07-13 10:27:42,832] INFO: Socket refused connection, running socketless

**Comment by allendoss** [comment]
Had the same error running `test.py` today

**Comment by shridhar-pivotchain** [comment]
are you running code on the instance?

**Comment by allendoss** [comment]
Nope, running it on my local machine for now and get the same error

**Comment by shridhar-pivotchain** [comment]
run command
'python3 -m visdom.server' 
on the terminal and  then type 
'http://localhost:8097' in your browser 
this will help you solve your connection problem

**Comment by oukohou** [comment]
> run command
'python3 -m visdom.server'
on the terminal and then type
'http://localhost:8097' in your browser
this will help you solve your connection problem

for me @shridhar-pivotchain 's this method works.

**Comment by TarzanWonder** [comment]
can you please provide your directory structure?

**Comment by HelixNGC7293** [comment]
python -m visdom.server
works for me at Windows Anaconda
