### ISSUE TITLE
Error when running test.py on non-CUDA system

### ISSUE THREAD

**Issue by paulpoloniewicz** [KupynOrest/DeblurGAN#89]
Hi. I am trying to run DeblurGAN on a non-CUDA system. I installed the non-CUDA version pf pytorch. Here the error I get:

ubi@ubi-VirtualBox:~/Dev/DeblurGAN-master$ python3 test.py --dataroot ./images/animation3.gif --model test --dataset_mode single --learn_residual
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=32 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    opt = TestOptions().parse()
  File "/home/ubi/Dev/DeblurGAN-master/options/base_options.py", line 61, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/home/ubi/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:32

Is there an option I need to set to get this to work?

**Comment by paulpoloniewicz** [comment]
Never mind - found it.
