### ISSUE TITLE
No module named util

### ISSUE THREAD

**Issue by liupengfei1234** [KupynOrest/DeblurGAN#95]
Hi @KupynOrest , thanks for releasing your code for both training and test.
When I run the demo, it occurs error as follows. Can you help me？Thank you！
bacon@bacon:~/lpf/DeblurGAN-master$ python test.py --dataroot /home/bacon/lpf/DeblurGAN-master/ima  --model test --dataset_mode single
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from options.test_options import TestOptions
  File "/home/bacon/lpf/DeblurGAN-master/options/test_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/home/bacon/lpf/DeblurGAN-master/options/base_options.py", line 3, in <module>
    from util import util
ImportError: No module named util

**Comment by MarStarck** [comment]
set PYTHONPATH to be your DeblurGAN dir.
